--- #YAML:1.0
name:                Dpchrist-File-Newest
version:             1.013
abstract:            ~
license:             ~
author:              
    - David Christensen <dpchrist@holgerdanske.com>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
